import mongoose, { Schema, Document, Model } from "mongoose";

// ─────────────────────────────────────────────
// 1. CONTENT DRAFTS MODEL
// ─────────────────────────────────────────────

/** Represents a single platform's content payload inside a Draft. */
export interface IPlatformContent {
  platform: "newsletter" | "linkedin" | "twitter" | "instagram" | "whatsapp";
  /** The full text / body for this platform. */
  content: string;
  /** Optional: published URL returned from the platform API after publishing. */
  publishedUrl?: string;
}

export interface IContentDraft extends Document {
  topic: string;
  status: "draft" | "approved" | "published";
  platforms: IPlatformContent[];
  /** Metadata returned by publishing APIs (keyed by platform name). */
  publishMetadata: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

const PlatformContentSchema = new Schema<IPlatformContent>(
  {
    platform: {
      type: String,
      enum: ["newsletter", "linkedin", "twitter", "instagram", "whatsapp"],
      required: true,
    },
    content: { type: String, required: true },
    publishedUrl: { type: String },
  },
  { _id: false }
);

const ContentDraftSchema = new Schema<IContentDraft>(
  {
    topic: { type: String, required: true, trim: true, index: true },
    status: {
      type: String,
      enum: ["draft", "approved", "published"],
      default: "draft",
      index: true,
    },
    platforms: {
      type: [PlatformContentSchema],
      default: [],
    },
    publishMetadata: {
      type: Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true, // Automatically manages createdAt & updatedAt
    versionKey: false,
  }
);

export const ContentDraft: Model<IContentDraft> = mongoose.model<IContentDraft>(
  "ContentDraft",
  ContentDraftSchema
);

// ─────────────────────────────────────────────
// 2. RESEARCH LOGS MODEL
// ─────────────────────────────────────────────

export interface IResearchSource {
  source: "rss" | "manual";
  url?: string;
  rawData: string;
}

export interface IResearchLog extends Document {
  topic: string;
  sources: IResearchSource[];
  /** A compiled summary generated by combining all sources. */
  synthesizedSummary: string;
  createdAt: Date;
  updatedAt: Date;
}

const ResearchSourceSchema = new Schema<IResearchSource>(
  {
    source: {
      type: String,
      enum: ["rss", "manual"],
      required: true,
    },
    url: { type: String },
    rawData: { type: String, required: true },
  },
  { _id: false }
);

const ResearchLogSchema = new Schema<IResearchLog>(
  {
    topic: { type: String, required: true, trim: true, index: true },
    sources: { type: [ResearchSourceSchema], default: [] },
    synthesizedSummary: { type: String, default: "" },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

export const ResearchLog: Model<IResearchLog> = mongoose.model<IResearchLog>(
  "ResearchLog",
  ResearchLogSchema
);

// ─────────────────────────────────────────────
// 3. ANALYTICS LOGS MODEL
// ─────────────────────────────────────────────

export interface IAnalyticsEntry extends Document {
  draftId?: string;
  platform: string;
  timeframe: string;
  metrics: Record<string, number | string>;
  notionSyncedAt?: Date;
  createdAt: Date;
}

const AnalyticsEntrySchema = new Schema<IAnalyticsEntry>(
  {
    draftId: { type: String, index: true },
    platform: { type: String, required: true },
    timeframe: { type: String, required: true },
    metrics: { type: Schema.Types.Mixed, default: {} },
    notionSyncedAt: { type: Date },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

export const AnalyticsEntry: Model<IAnalyticsEntry> =
  mongoose.model<IAnalyticsEntry>("AnalyticsEntry", AnalyticsEntrySchema);
